### ISSUE TITLE
Enable custom keybindings for all options

### ISSUE THREAD

**Issue by ethanclevenger91** [msansoni/atom-path-copy#2]
Related to #1, it'd be awesome to set keybindings to any of the various commands we'd like. Rather than just copying the current tab's full path, set up a keybinding for copying the current tab's relative path, for instance.

**Comment by msansoni** [comment]
Hi Ethan,

Great idea! I will include the functionality in the next version 0.13.0. 

One consideration is that when the commands are selected by the context menu on the tabs bar, the tab selected is the tab underneath the cursor, this allows the user to copy the path of a tab which isn't necessarily active. However when using the keyboard shortcuts, this will only apply to the active tab. Therefore we need to add some intelligence to the functions when the command is called, to describe where the event was emitted, either from the context menu or keyboard shortcut, in order to evaluate which tab URI to parse.

In the short-term I will create extra methods so the keybindings call separate methods to the context-menu. However this isn't the prettiest solution, given they both are doing pretty much the same thing. If you have any ideas on how to tell the method the source of the event/a better solution let me know!

**Comment by msansoni** [comment]
Release published, with enhancement included.
Will accept any PRs to improve implementation of separation for key-bindings/context-menu calls.
